title: Blog title
author: Rooty
email: blackrooty@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write description. 

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
<<<<<<< HEAD

=======
>>>>>>> master
theme: jekyll-theme-midnight
